services:
  inventory-db:
    image: postgres:16-alpine
    container_name: inventory-db
    environment:
      POSTGRES_DB: inventory
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - inventory-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d inventory"]
      interval: 5s
      timeout: 5s
      retries: 10

  billing-db:
    image: postgres:16-alpine
    container_name: billing-db
    environment:
      POSTGRES_DB: billing
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - billing-db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d billing"]
      interval: 5s
      timeout: 5s
      retries: 10

  inventory-api:
    build:
      context: ./backend/Inventory.Api
      dockerfile: Dockerfile
    container_name: inventory-api
    ports:
      - "5001:8080"
    environment:
      - ConnectionStrings__InventoryDb=Host=inventory-db;Port=5432;Database=inventory;Username=postgres;Password=postgres
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      inventory-db:
        condition: service_healthy

  billing-api:
    build:
      context: ./backend/Billing.Api
      dockerfile: Dockerfile
    container_name: billing-api
    ports:
      - "5002:8080"
    environment:
      - ConnectionStrings__BillingDb=Host=billing-db;Port=5432;Database=billing;Username=postgres;Password=postgres
      - InventoryApi__BaseUrl=http://inventory-api:8080/
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      billing-db:
        condition: service_healthy
      inventory-api:
        condition: service_started

  angular-app:
    build:
      context: ./frontend/notas-fiscais-app
      dockerfile: Dockerfile
    container_name: angular-app
    ports:
      - "4200:80"
    depends_on:
      - inventory-api
      - billing-api

volumes:
  inventory-db-data:
  billing-db-data:
